<div id="footer" class="fixedContainer">
	<div class="footerSitemap">
		<dl>
			<dt><a href="">Media</a></dt>
		    <dd><a href="">Collective Network</a></dd>
		    <dd><a href="">Directive Network</a></dd>
		    <dd><a href="">Collective Video</a></dd>
		    <dd><a href="">What Worked this Week</a></dd>
		</dl>
		<dl>
			<dt><a href="">Technology</a></dt>
		    <dd><a href="">AMP</a></dd>
		    <dd><a href="">AMP Audience Cloud</a></dd>
		    <dd><a href="">AMP Network Administration</a></dd>
		    <dd><a href="">AMP Reach Extension</a></dd>
		    <dd><a href="">AMP Targeting Suite</a></dd>
		    <dd><a href="">AMP Reporting &amp; Analytics</a></dd>
		</dl>
		<dl>
			<dt><a href="">Insight</a></dt>
		    <dd><a href="">What Worked this Week</a></dd>
		    <dd><a href="">Collective Insights</a></dd>
		    <dd><a href="">Audience HD</a></dd>
		    <dd><a href="">Engagement HD</a></dd>
		    <dd><a href="">Branding HD</a></dd>
		    <dd><a href="">Search + Display HD</a></dd>
		</dl>
		<dl>
			<dt><a href="">Creative</a></dt>
		    <dd><a href="">OggiFinogi</a></dd>
		    <dd><a href="">Rich Media</a></dd>
		    <dd><a href="">Dynamic Ads</a></dd>
		    <dd><a href="">Video</a></dd>
		    <dd><a href="">IAB Standard Units</a></dd>
		</dl>
		<dl>
			<dt><a href="">About Us</a></dt>
		    <dd><a href="">Management Team</a></dd>
		    <dd><a href="">News</a></dd>
		    <dd><a href="">Events</a></dd>
		    <dd><a href="">Careers</a></dd>
		</dl>
		<dl>
		    <dd><a href="">Contact Us</a></dd>
		    <dd><a href="https://amp.collective.com/" target="_blank">Client Log-in</a></dd>
		</dl>
	</div>
	<ul class="footerLogos">
		<li class="aaaa">AAAA logo</li> 
		<li class="iab">AIB logo</li>
		<li class="nai">NAI logo</li> 
		<li class="opa">opa logo</li>
		<li class="trust_e">truste logo</li>
	</ul>
	<div class="footerItems">
		<a href="privacy.php">Privacy Policy</a> | <a href="legal.php">Legal Terms</a> | Copyright 2009
	</div>
</div><!-- Footer -->